// <auto-generated />
using System;
using AutomoveisVendasApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomoveisVendasApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260417112530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Carro", b =>
                {
                    b.Property<int>("CarroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Vendido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("CarroId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Carros", (string)null);

                    b.HasData(
                        new
                        {
                            CarroId = 1,
                            Ano = 2022,
                            Marca = "Honda",
                            Modelo = "Civic",
                            Placa = "ABC-1234",
                            Valor = 95000m,
                            Vendido = true
                        },
                        new
                        {
                            CarroId = 2,
                            Ano = 2023,
                            Marca = "Toyota",
                            Modelo = "Corolla",
                            Placa = "XYZ-5678",
                            Valor = 110000m,
                            Vendido = false
                        });
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Email = "joao@email.com",
                            Nome = "João Silva",
                            Telefone = "11999990001"
                        },
                        new
                        {
                            ClienteId = 2,
                            Email = "maria@email.com",
                            Nome = "Maria Souza",
                            Telefone = "11999990002"
                        });
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Moto", b =>
                {
                    b.Property<int>("MotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Vendida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("MotoId");

                    b.ToTable("Motos", (string)null);

                    b.HasData(
                        new
                        {
                            MotoId = 1,
                            Ano = 2022,
                            Marca = "Kawasaki",
                            Modelo = "Ninja 400",
                            Valor = 35000m,
                            Vendida = false
                        },
                        new
                        {
                            MotoId = 2,
                            Ano = 2023,
                            Marca = "Honda",
                            Modelo = "CB 500F",
                            Valor = 30000m,
                            Vendida = false
                        });
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("PagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PagamentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("Pagamentos", (string)null);

                    b.HasData(
                        new
                        {
                            PagamentoId = 1,
                            DataPagamento = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Financiamento",
                            Valor = 95000m,
                            VendaId = 1
                        });
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CarroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pendente");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VendaId");

                    b.HasIndex("CarroId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MotoId");

                    b.ToTable("Vendas", (string)null);

                    b.HasData(
                        new
                        {
                            VendaId = 1,
                            CarroId = 1,
                            ClienteId = 1,
                            DataVenda = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Finalizada",
                            ValorTotal = 95000m
                        });
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("AutomoveisVendasApi.Domain.Entities.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Venda", b =>
                {
                    b.HasOne("AutomoveisVendasApi.Domain.Entities.Carro", "Carro")
                        .WithMany("Vendas")
                        .HasForeignKey("CarroId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AutomoveisVendasApi.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AutomoveisVendasApi.Domain.Entities.Moto", "Moto")
                        .WithMany("Vendas")
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Carro");

                    b.Navigation("Cliente");

                    b.Navigation("Moto");
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Carro", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Moto", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("AutomoveisVendasApi.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
